version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public/php/:/var/www/html/php/
      - ./public/index.php:/var/www/html/index.php
      - ./public/js/:/var/www/html/js/
      - ./config:/var/www/config/
    secrets: 
      - .env
    depends_on:
      - db
    ports:
      - '80:80'
    networks: 
      - backend
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./secrets/.env
    volumes:
      - ./db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - '3306:3306/tcp'
    networks:
      - backend

networks: 
  backend:
    driver: bridge
    name: backend
  
secrets: 
  .env:
    file: ./secrets/.env
